name: Create Release
 
on:
  push:
    branches:
      - main

jobs:
  create_git_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Tag
        id: create-tag
        run: |
          echo "$(TZ=Asia/Tokyo date +%Y%m%d_%H%M%S)" > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
          echo "::set-output name=tag-name::$(cat TAG_NAME)"
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.tag-name }}
          release_name: Release/${{ steps.create-tag.outputs.tag-name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
